name: Raise issue if exe file encountered in commit

on: 
  push:
    branches:
      - 'test'

jobs:
  check-exe-file:

    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: test for .exe files and raise issue if .exe file found
        run: |
          python test_no_exe_files.py
          if: ${{ echo $? == "false" }}
          - name: raise github issue
            uses: imjohnbo/issue-bot@v3.0
            with:
              title: "User checked in exe file in commit."
              body: | 
                - [ ] Checked in exe file while commiting to the test branch
                - [ ] Remove the files having .exe extension and commit again

            pinned: false
            close-previous: false


            
