name: Print the list of commits and users in a pull request

on: 
  pull_request
    
jobs:
  print-pr-details:

    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - name: print author name
        run: |
         git log --format='%an'
         git shortlog -s -n