name: Print the name of the user submitting the pull request

on: 
  pull_request
    
jobs:
  print-user-name:

    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - name: print author name
        run: git log --format='%an'